RawData <- read.table("household_power_consumption.txt",header=TRUE,na.strings="?",sep=";")
Feb12Data<-subset(RawData, {(RawData$Date == "2/2/2007")|(RawData$Date == "1/2/2007")})
DateTime<-paste(Feb12Data$Date, Feb12Data$Time)
Date_Time<- strptime(DateTime, format="%e/%m/%Y %H:%M:%S")
DateTimeDF <- cbind(Date_Time, Feb12Data)

par(mfcol=c(1,1))
png(file="plot3.png")
with(DateTimeDF, plot(Sub_metering_1 ~ Date_Time, xlab="", ylab="Energy sub metering", type="n"))
lines(DateTimeDF$Date_Time,DateTimeDF$Sub_metering_1,col="black")
lines(DateTimeDF$Date_Time,DateTimeDF$Sub_metering_2,col="red")
lines(DateTimeDF$Date_Time,DateTimeDF$Sub_metering_3,col="blue")
legend("topright",lty=1, col=c("black","red", "blue"),legend=c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))
dev.off()
